# Generated by Django 5.2.4 on 2025-07-09 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='puntuacion',
            new_name='puntaje',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_publicacion',
            new_name='fecha_lanzamiento',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='url_pdf',
            new_name='url_libro',
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('libro', 'usuario')},
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='libros.libro'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libros.genero'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libros.autor'),
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='resenha',
        ),
    ]
